// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKYNL-rRj2jIHPOfpLIB09pzgXvmpv2zI',
    appId: '1:56234174900:web:0f441264474cc593ddeae1',
    messagingSenderId: '56234174900',
    projectId: 'aitechpredict',
    authDomain: 'aitechpredict.firebaseapp.com',
    storageBucket: 'aitechpredict.appspot.com',
    measurementId: 'G-7HXFYX57ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJee7Hj9ZGMDA2uJimQiKYF-g12s1oZro',
    appId: '1:56234174900:android:0ff73e4ee1d96197ddeae1',
    messagingSenderId: '56234174900',
    projectId: 'aitechpredict',
    storageBucket: 'aitechpredict.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKYNL-rRj2jIHPOfpLIB09pzgXvmpv2zI',
    appId: '1:56234174900:web:9d873a5c8f05ab90ddeae1',
    messagingSenderId: '56234174900',
    projectId: 'aitechpredict',
    authDomain: 'aitechpredict.firebaseapp.com',
    storageBucket: 'aitechpredict.appspot.com',
    measurementId: 'G-E9MTSSYBCW',
  );
}
